### ISSUE TITLE
Ability to match on particular method signatures

### ISSUE THREAD

**Issue by jmle** [konveyor/java-analyzer-bundle#36]
The tool should be able to match on particular method signatures, ie, match on
```Integer.getInteger(java.lang.Integer, java.lang.String)```
but not on
```Integer.getInteger(java.lang.Integer)```.

**Comment by shawn-hurley** [comment]
@jmle transferred the issue because I think these issues should live here when we finally get to the external providers.

WDYT? I can move it back if you disagree significantly.

**Comment by shawn-hurley** [comment]
Adding a link to the example from windup: https://github.com/windup/windup-rulesets/blob/master/rules/rules-reviewed/eap8/eap7/javax-to-jakarta-servlet.windup.xml#L154-L166
